"""Plot diagnostics generated by ``bayesian-ach-design``."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("result_directory", type=Path)
    args = parser.parse_args()

    with (args.result_directory / "design_diagnostics.csv").open(encoding="utf-8") as handle:
        diagnostics = list(csv.DictReader(handle))
    with (args.result_directory / "design_recovery.csv").open(encoding="utf-8") as handle:
        recovery = list(csv.DictReader(handle))

    names = [row["design"] for row in diagnostics]
    residuals = [float(row["minimum_pairwise_residual_variance"]) for row in diagnostics]
    plt.figure(figsize=(7, 4))
    plt.bar(names, residuals)
    plt.ylabel("Minimum pairwise residual variance")
    plt.xticks(rotation=25, ha="right")
    plt.tight_layout()
    plt.show()

    for design in names:
        selected = [row for row in recovery if row["design"] == design]
        plt.figure(figsize=(8, 4))
        plt.bar(
            [row["generator"] for row in selected],
            [float(row["recovery_rate"]) for row in selected],
        )
        plt.ylim(0.0, 1.0)
        plt.ylabel("Held-out recovery rate")
        plt.title(design)
        plt.xticks(rotation=35, ha="right")
        plt.tight_layout()
        plt.show()


if __name__ == "__main__":
    main()
