"""Plot closed-loop model scores generated by the benchmark CLI."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("fits_csv", type=Path)
    args = parser.parse_args()

    with args.fits_csv.open(encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    generators = sorted({row["generator"] for row in rows})
    for generator in generators:
        selected = [row for row in rows if row["generator"] == generator]
        selected.sort(key=lambda row: int(row["rank"]))
        models = [row["model"] for row in selected]
        scores = [float(row["test_mean_log_predictive"]) for row in selected]

        plt.figure(figsize=(10, 4))
        plt.bar(models, scores)
        plt.title(f"Closed-loop generator: {generator}")
        plt.ylabel("Held-out mean log predictive density")
        plt.xticks(rotation=45, ha="right")
        plt.tight_layout()
        plt.show()


if __name__ == "__main__":
    main()
