"""Bayesian optimal experimental design for discriminating ACh hypotheses.

The module deliberately separates two questions:

1. which computational signal is generated by a controlled manipulation; and
2. whether that signal remains identifiable after indicator dynamics, nuisance
   variation, subject/session offsets, and measurement noise.

All design criteria are prospective. Outcomes are never used to select the
schedule evaluated on those same outcomes.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations
from typing import Final, Iterable, Mapping, Sequence

import numpy as np
from numpy.typing import NDArray
from scipy.special import logsumexp

HYPOTHESIS_NAMES: Final[tuple[str, ...]] = (
    "predictive_surprise",
    "bayesian_gain",
    "rational_update",
    "structural_change",
    "context_information",
    "sensor_fault_information",
)


@dataclass(frozen=True, slots=True)
class TrialCondition:
    """One controlled transition-observation condition.

    Probability, confidence, reset compatibility, context evidence, and
    sensor-fault evidence can be manipulated independently. Likelihood-ratio
    fields favour the named alternative explanation when larger than one.
    """

    name: str
    predictive_probability: float
    concentration: float
    reset_probability: float
    change_hazard: float
    context_prior: float
    context_likelihood_ratio: float
    sensor_fault_prior: float
    sensor_likelihood_ratio: float
    nuisance_level: float = 0.0

    def validate(self) -> None:
        for name, value in (
            ("predictive_probability", self.predictive_probability),
            ("reset_probability", self.reset_probability),
            ("change_hazard", self.change_hazard),
            ("context_prior", self.context_prior),
            ("sensor_fault_prior", self.sensor_fault_prior),
        ):
            if not np.isfinite(value) or not 0.0 < value < 1.0:
                raise ValueError(f"{name} must be finite and lie in (0, 1)")
        if not np.isfinite(self.concentration) or self.concentration <= 0.0:
            raise ValueError("concentration must be finite and positive")
        for name, value in (
            ("context_likelihood_ratio", self.context_likelihood_ratio),
            ("sensor_likelihood_ratio", self.sensor_likelihood_ratio),
        ):
            if not np.isfinite(value) or value <= 0.0:
                raise ValueError(f"{name} must be finite and positive")
        if not np.isfinite(self.nuisance_level):
            raise ValueError("nuisance_level must be finite")


@dataclass(frozen=True, slots=True)
class DesignConfig:
    """Prior-predictive model used by the design criterion."""

    trial_interval: float = 2.0
    tau_rise: float = 0.40
    tau_decay: float = 1.60
    noise_std: float = 1.0
    signal_mean: float = 0.75
    signal_std: float = 0.25
    intercept_std: float = 1.0
    nuisance_std: float = 0.50
    robust_sensor_grid: tuple[tuple[float, float], ...] = (
        (0.30, 1.20),
        (0.40, 1.60),
        (0.60, 2.40),
    )

    def validate(self) -> None:
        for name, value in (
            ("trial_interval", self.trial_interval),
            ("tau_rise", self.tau_rise),
            ("tau_decay", self.tau_decay),
            ("noise_std", self.noise_std),
            ("signal_std", self.signal_std),
            ("intercept_std", self.intercept_std),
            ("nuisance_std", self.nuisance_std),
        ):
            if not np.isfinite(value) or value <= 0.0:
                raise ValueError(f"{name} must be finite and positive")
        if self.tau_rise >= self.tau_decay:
            raise ValueError("require tau_rise < tau_decay")
        if not np.isfinite(self.signal_mean):
            raise ValueError("signal_mean must be finite")
        if not self.robust_sensor_grid:
            raise ValueError("robust_sensor_grid must not be empty")
        for tau_rise, tau_decay in self.robust_sensor_grid:
            if not 0.0 < tau_rise < tau_decay:
                raise ValueError("each robust sensor pair must satisfy 0 < rise < decay")


@dataclass(frozen=True, slots=True)
class GaussianPredictive:
    """Marginal Gaussian predictive distribution under one hypothesis."""

    mean: NDArray[np.float64]
    covariance: NDArray[np.float64]
    cholesky: NDArray[np.float64]
    log_determinant: float


@dataclass(frozen=True, slots=True)
class DesignEvaluation:
    """Prospective performance summary for one fixed schedule."""

    name: str
    n_trials: int
    expected_information_gain_nats: float
    robust_min_pairwise_symmetric_kl: float
    recovery_accuracy: float
    mean_true_hypothesis_probability: float
    mean_posterior_entropy_nats: float
    schedule: tuple[str, ...]

    def as_dict(self) -> dict[str, float | int | str | list[str]]:
        return {
            "name": self.name,
            "n_trials": self.n_trials,
            "expected_information_gain_nats": self.expected_information_gain_nats,
            "robust_min_pairwise_symmetric_kl": self.robust_min_pairwise_symmetric_kl,
            "recovery_accuracy": self.recovery_accuracy,
            "mean_true_hypothesis_probability": self.mean_true_hypothesis_probability,
            "mean_posterior_entropy_nats": self.mean_posterior_entropy_nats,
            "schedule": list(self.schedule),
        }


def _bernoulli_posterior(prior: float, likelihood_ratio: float) -> float:
    numerator = prior * likelihood_ratio
    return float(numerator / (numerator + 1.0 - prior))


def _bernoulli_kl(posterior: float, prior: float) -> float:
    return float(
        posterior * np.log(posterior / prior)
        + (1.0 - posterior) * np.log((1.0 - posterior) / (1.0 - prior))
    )


def condition_signals(condition: TrialCondition) -> dict[str, float]:
    """Return six distinct candidate ACh signals for one condition."""

    condition.validate()
    probability = condition.predictive_probability
    innovation = np.sqrt(2.0) * (1.0 - probability)
    gain = 1.0 / (condition.concentration + 1.0)
    change_numerator = condition.change_hazard * condition.reset_probability
    change_denominator = (
        (1.0 - condition.change_hazard) * probability + change_numerator
    )
    context_posterior = _bernoulli_posterior(
        condition.context_prior,
        condition.context_likelihood_ratio,
    )
    sensor_posterior = _bernoulli_posterior(
        condition.sensor_fault_prior,
        condition.sensor_likelihood_ratio,
    )
    return {
        "predictive_surprise": float(-np.log(probability)),
        "bayesian_gain": float(gain),
        "rational_update": float(gain * innovation),
        "structural_change": float(change_numerator / change_denominator),
        "context_information": _bernoulli_kl(context_posterior, condition.context_prior),
        "sensor_fault_information": _bernoulli_kl(
            sensor_posterior,
            condition.sensor_fault_prior,
        ),
    }


def fractional_factorial_conditions() -> tuple[TrialCondition, ...]:
    """Return a balanced 16-condition identifying design library.

    Four independent binary factors control surprise, confidence, reset
    compatibility, and context evidence. Sensor-fault evidence and nuisance
    level use orthogonal interaction columns, yielding a compact fractional
    factorial library with balanced main effects.
    """

    conditions: list[TrialCondition] = []
    for index in range(16):
        a = (index >> 0) & 1
        b = (index >> 1) & 1
        c = (index >> 2) & 1
        d = (index >> 3) & 1
        sensor_bit = a ^ b ^ c
        nuisance_bit = a ^ c ^ d
        conditions.append(
            TrialCondition(
                name=f"F{index:02d}",
                predictive_probability=0.20 if a else 0.80,
                concentration=4.0 if b else 128.0,
                reset_probability=0.80 if c else 0.20,
                change_hazard=0.08,
                context_prior=0.08,
                context_likelihood_ratio=8.0 if d else 0.125,
                sensor_fault_prior=0.08,
                sensor_likelihood_ratio=8.0 if sensor_bit else 0.125,
                nuisance_level=1.0 if nuisance_bit else -1.0,
            )
        )
    return tuple(conditions)


def novelty_only_conditions() -> tuple[TrialCondition, TrialCondition]:
    """Return the confounded familiar-versus-novel contrast."""

    familiar = TrialCondition(
        name="familiar",
        predictive_probability=0.80,
        concentration=128.0,
        reset_probability=0.20,
        change_hazard=0.02,
        context_prior=0.02,
        context_likelihood_ratio=0.20,
        sensor_fault_prior=0.02,
        sensor_likelihood_ratio=0.20,
        nuisance_level=-1.0,
    )
    novel = TrialCondition(
        name="novel",
        predictive_probability=0.20,
        concentration=4.0,
        reset_probability=0.80,
        change_hazard=0.08,
        context_prior=0.08,
        context_likelihood_ratio=8.0,
        sensor_fault_prior=0.08,
        sensor_likelihood_ratio=8.0,
        nuisance_level=1.0,
    )
    return familiar, novel


def matched_confidence_conditions() -> tuple[TrialCondition, ...]:
    """Return a 2x2 probability-by-confidence design."""

    conditions: list[TrialCondition] = []
    for probability_label, probability in (("common", 0.80), ("rare", 0.20)):
        for confidence_label, concentration in (("lowconf", 4.0), ("highconf", 128.0)):
            conditions.append(
                TrialCondition(
                    name=f"{probability_label}_{confidence_label}",
                    predictive_probability=probability,
                    concentration=concentration,
                    reset_probability=0.50,
                    change_hazard=0.05,
                    context_prior=0.05,
                    context_likelihood_ratio=1.0,
                    sensor_fault_prior=0.05,
                    sensor_likelihood_ratio=1.0,
                    nuisance_level=0.0,
                )
            )
    return tuple(conditions)


def _reference_statistics(
    reference_conditions: Sequence[TrialCondition],
) -> dict[str, tuple[float, float]]:
    rows = [condition_signals(condition) for condition in reference_conditions]
    statistics: dict[str, tuple[float, float]] = {}
    for hypothesis in HYPOTHESIS_NAMES:
        values = np.asarray([row[hypothesis] for row in rows], dtype=float)
        scale = max(float(np.std(values)), 1e-8)
        statistics[hypothesis] = (float(np.mean(values)), scale)
    return statistics


def causal_sensor_matrix(
    n_trials: int,
    *,
    trial_interval: float,
    tau_rise: float,
    tau_decay: float,
) -> NDArray[np.float64]:
    """Return a lower-triangular, peak-normalized indicator convolution matrix."""

    if n_trials < 1:
        raise ValueError("n_trials must be positive")
    if not 0.0 < tau_rise < tau_decay:
        raise ValueError("require 0 < tau_rise < tau_decay")
    lags = (np.arange(n_trials, dtype=float) + 1.0) * trial_interval
    kernel = np.exp(-lags / tau_decay) - np.exp(-lags / tau_rise)
    peak = float(np.max(kernel))
    if peak <= 0.0:
        raise ValueError("invalid sensor kernel")
    kernel /= peak
    matrix = np.zeros((n_trials, n_trials), dtype=float)
    for row in range(n_trials):
        for column in range(row + 1):
            matrix[row, column] = kernel[row - column]
    return matrix


def _hypothesis_drive(
    schedule: Sequence[TrialCondition],
    hypothesis: str,
    *,
    reference_conditions: Sequence[TrialCondition],
    sensor_matrix: NDArray[np.float64],
) -> NDArray[np.float64]:
    if hypothesis not in HYPOTHESIS_NAMES:
        raise ValueError(f"unknown hypothesis {hypothesis!r}")
    mean, scale = _reference_statistics(reference_conditions)[hypothesis]
    raw = np.asarray(
        [(condition_signals(condition)[hypothesis] - mean) / scale for condition in schedule],
        dtype=float,
    )
    return np.asarray(sensor_matrix @ raw, dtype=float)


def predictive_distribution(
    schedule: Sequence[TrialCondition],
    hypothesis: str,
    config: DesignConfig,
    *,
    reference_conditions: Sequence[TrialCondition] | None = None,
    tau_rise: float | None = None,
    tau_decay: float | None = None,
) -> GaussianPredictive:
    """Marginalize signal amplitude and shared nuisance coefficients exactly."""

    config.validate()
    if not schedule:
        raise ValueError("schedule must not be empty")
    reference = tuple(reference_conditions or fractional_factorial_conditions())
    rise = config.tau_rise if tau_rise is None else tau_rise
    decay = config.tau_decay if tau_decay is None else tau_decay
    sensor = causal_sensor_matrix(
        len(schedule),
        trial_interval=config.trial_interval,
        tau_rise=rise,
        tau_decay=decay,
    )
    drive = _hypothesis_drive(
        schedule,
        hypothesis,
        reference_conditions=reference,
        sensor_matrix=sensor,
    )
    nuisance = np.asarray([condition.nuisance_level for condition in schedule], dtype=float)
    nuisance_design = np.column_stack((np.ones(len(schedule)), nuisance))
    nuisance_variances = np.asarray(
        [config.intercept_std**2, config.nuisance_std**2],
        dtype=float,
    )
    # Unknown response gain must not identify hypotheses merely because their
    # numerical units differ. Remove nuisance and normalize temporal shape.
    nuisance_projection, *_ = np.linalg.lstsq(nuisance_design, drive, rcond=None)
    drive = drive - nuisance_design @ nuisance_projection
    drive_norm = float(np.linalg.norm(drive))
    if drive_norm > 1e-10:
        drive = drive / drive_norm
    else:
        drive = np.zeros_like(drive)
    mean = config.signal_mean * drive
    covariance = (
        config.noise_std**2 * np.eye(len(schedule))
        + config.signal_std**2 * np.outer(drive, drive)
        + (nuisance_design * nuisance_variances) @ nuisance_design.T
    )
    covariance += 1e-9 * np.eye(len(schedule))
    cholesky = np.linalg.cholesky(covariance)
    return GaussianPredictive(
        mean=np.asarray(mean, dtype=float),
        covariance=np.asarray(covariance, dtype=float),
        cholesky=np.asarray(cholesky, dtype=float),
        log_determinant=float(2.0 * np.sum(np.log(np.diag(cholesky)))),
    )


def _gaussian_logpdf(
    samples: NDArray[np.float64], distribution: GaussianPredictive
) -> NDArray[np.float64]:
    centered = np.asarray(samples, dtype=float) - distribution.mean
    solved = np.linalg.solve(distribution.cholesky, centered.T).T
    quadratic = np.sum(solved**2, axis=1)
    dimension = distribution.mean.size
    return np.asarray(
        -0.5
        * (
            dimension * np.log(2.0 * np.pi)
            + distribution.log_determinant
            + quadratic
        ),
        dtype=float,
    )


def _gaussian_kl(first: GaussianPredictive, second: GaussianPredictive) -> float:
    dimension = first.mean.size
    inverse_second_first = np.linalg.solve(second.covariance, first.covariance)
    delta = second.mean - first.mean
    quadratic = float(delta @ np.linalg.solve(second.covariance, delta))
    return 0.5 * float(
        np.trace(inverse_second_first)
        + quadratic
        - dimension
        + second.log_determinant
        - first.log_determinant
    )


def min_pairwise_symmetric_kl(
    schedule: Sequence[TrialCondition],
    config: DesignConfig,
    *,
    reference_conditions: Sequence[TrialCondition] | None = None,
    robust: bool = True,
) -> float:
    """Return the worst-separated hypothesis pair, optionally over sensor kinetics."""

    config.validate()
    sensor_grid = (
        config.robust_sensor_grid
        if robust
        else ((config.tau_rise, config.tau_decay),)
    )
    values: list[float] = []
    for tau_rise, tau_decay in sensor_grid:
        distributions = {
            hypothesis: predictive_distribution(
                schedule,
                hypothesis,
                config,
                reference_conditions=reference_conditions,
                tau_rise=tau_rise,
                tau_decay=tau_decay,
            )
            for hypothesis in HYPOTHESIS_NAMES
        }
        pair_values = []
        for first_name, second_name in combinations(HYPOTHESIS_NAMES, 2):
            first = distributions[first_name]
            second = distributions[second_name]
            pair_values.append(
                0.5 * (_gaussian_kl(first, second) + _gaussian_kl(second, first))
            )
        values.append(min(pair_values))
    return float(min(values))


def expected_information_gain(
    schedule: Sequence[TrialCondition],
    config: DesignConfig,
    *,
    reference_conditions: Sequence[TrialCondition] | None = None,
    samples_per_hypothesis: int = 512,
    seed: int = 7,
) -> float:
    """Estimate ``I(H;Y | schedule)`` in nats under a uniform hypothesis prior."""

    if samples_per_hypothesis < 1:
        raise ValueError("samples_per_hypothesis must be positive")
    distributions = [
        predictive_distribution(
            schedule,
            hypothesis,
            config,
            reference_conditions=reference_conditions,
        )
        for hypothesis in HYPOTHESIS_NAMES
    ]
    log_prior = -np.log(len(distributions))
    rng = np.random.default_rng(seed)
    contributions: list[float] = []
    for true_index, distribution in enumerate(distributions):
        standard = rng.normal(size=(samples_per_hypothesis, len(schedule)))
        samples = distribution.mean + standard @ distribution.cholesky.T
        log_likelihoods = np.column_stack(
            [_gaussian_logpdf(samples, candidate) for candidate in distributions]
        )
        log_mixture = logsumexp(log_likelihoods + log_prior, axis=1)
        contributions.extend((log_likelihoods[:, true_index] - log_mixture).tolist())
    return float(np.mean(contributions))


def hypothesis_log_likelihoods(
    observations: NDArray[np.float64],
    schedule: Sequence[TrialCondition],
    config: DesignConfig,
    *,
    reference_conditions: Sequence[TrialCondition] | None = None,
) -> NDArray[np.float64]:
    """Return one marginal log likelihood per computational hypothesis."""

    sample = np.asarray(observations, dtype=float)
    if sample.shape != (len(schedule),):
        raise ValueError(
            f"observations must have shape ({len(schedule)},); got {sample.shape}"
        )
    return np.asarray(
        [
            _gaussian_logpdf(
                sample[None, :],
                predictive_distribution(
                    schedule,
                    hypothesis,
                    config,
                    reference_conditions=reference_conditions,
                ),
            )[0]
            for hypothesis in HYPOTHESIS_NAMES
        ],
        dtype=float,
    )


def posterior_probabilities(
    observations: NDArray[np.float64],
    schedule: Sequence[TrialCondition],
    config: DesignConfig,
    *,
    reference_conditions: Sequence[TrialCondition] | None = None,
) -> NDArray[np.float64]:
    """Return posterior hypothesis probabilities for one observation vector."""

    log_likelihood = hypothesis_log_likelihoods(
        observations,
        schedule,
        config,
        reference_conditions=reference_conditions,
    )
    return np.asarray(
        np.exp(log_likelihood - logsumexp(log_likelihood)), dtype=float
    )


def simulate_recovery(
    schedule: Sequence[TrialCondition],
    config: DesignConfig,
    *,
    reference_conditions: Sequence[TrialCondition] | None = None,
    replicates_per_hypothesis: int = 256,
    seed: int = 7,
) -> tuple[float, float, float]:
    """Return accuracy, true-model posterior mass, and posterior entropy."""

    if replicates_per_hypothesis < 1:
        raise ValueError("replicates_per_hypothesis must be positive")
    distributions = [
        predictive_distribution(
            schedule,
            hypothesis,
            config,
            reference_conditions=reference_conditions,
        )
        for hypothesis in HYPOTHESIS_NAMES
    ]
    rng = np.random.default_rng(seed)
    correct = 0
    true_probability: list[float] = []
    entropy: list[float] = []
    for true_index, distribution in enumerate(distributions):
        standard = rng.normal(size=(replicates_per_hypothesis, len(schedule)))
        samples = distribution.mean + standard @ distribution.cholesky.T
        log_likelihoods = np.column_stack(
            [_gaussian_logpdf(samples, candidate) for candidate in distributions]
        )
        posterior = np.exp(
            log_likelihoods - logsumexp(log_likelihoods, axis=1)[:, None]
        )
        correct += int(np.sum(np.argmax(posterior, axis=1) == true_index))
        true_probability.extend(posterior[:, true_index].tolist())
        entropy.extend(
            (
                -np.sum(
                    posterior * np.log(np.maximum(posterior, 1e-300)), axis=1
                )
            ).tolist()
        )
    total = len(distributions) * replicates_per_hypothesis
    return (
        correct / total,
        float(np.mean(true_probability)),
        float(np.mean(entropy)),
    )


def balanced_schedule(
    conditions: Sequence[TrialCondition], n_trials: int
) -> tuple[TrialCondition, ...]:
    """Repeat conditions in a deterministic balanced order."""

    if not conditions:
        raise ValueError("conditions must not be empty")
    if n_trials < 1:
        raise ValueError("n_trials must be positive")
    return tuple(conditions[index % len(conditions)] for index in range(n_trials))


def greedy_maximin_schedule(
    conditions: Sequence[TrialCondition],
    n_trials: int,
    config: DesignConfig,
    *,
    max_repeats_per_condition: int | None = None,
) -> tuple[TrialCondition, ...]:
    """Greedily maximize worst-case pairwise discrimination.

    The criterion is evaluated prospectively and robustly across the configured
    indicator-timescale grid. Ties are resolved deterministically.
    """

    if not conditions:
        raise ValueError("conditions must not be empty")
    if n_trials < 1:
        raise ValueError("n_trials must be positive")
    maximum = (
        n_trials if max_repeats_per_condition is None else max_repeats_per_condition
    )
    if maximum < 1:
        raise ValueError("max_repeats_per_condition must be positive")
    selected: list[TrialCondition] = []
    counts = {condition.name: 0 for condition in conditions}
    reference = tuple(conditions)
    for _ in range(n_trials):
        candidates: list[tuple[float, str, TrialCondition]] = []
        for condition in conditions:
            if counts[condition.name] >= maximum:
                continue
            proposed = (*selected, condition)
            score = min_pairwise_symmetric_kl(
                proposed,
                config,
                reference_conditions=reference,
                robust=True,
            )
            candidates.append((score, condition.name, condition))
        if not candidates:
            raise ValueError("repeat constraint makes the requested schedule impossible")
        _, _, winner = sorted(candidates, key=lambda item: (-item[0], item[1]))[0]
        selected.append(winner)
        counts[winner.name] += 1
    return tuple(selected)


def evaluate_schedule(
    name: str,
    schedule: Sequence[TrialCondition],
    config: DesignConfig,
    *,
    reference_conditions: Sequence[TrialCondition] | None = None,
    information_samples: int = 512,
    recovery_replicates: int = 256,
    seed: int = 7,
) -> DesignEvaluation:
    """Compute prospective discrimination metrics for a frozen schedule."""

    information = expected_information_gain(
        schedule,
        config,
        reference_conditions=reference_conditions,
        samples_per_hypothesis=information_samples,
        seed=seed,
    )
    accuracy, true_probability, entropy = simulate_recovery(
        schedule,
        config,
        reference_conditions=reference_conditions,
        replicates_per_hypothesis=recovery_replicates,
        seed=seed + 1,
    )
    return DesignEvaluation(
        name=name,
        n_trials=len(schedule),
        expected_information_gain_nats=information,
        robust_min_pairwise_symmetric_kl=min_pairwise_symmetric_kl(
            schedule,
            config,
            reference_conditions=reference_conditions,
            robust=True,
        ),
        recovery_accuracy=accuracy,
        mean_true_hypothesis_probability=true_probability,
        mean_posterior_entropy_nats=entropy,
        schedule=tuple(condition.name for condition in schedule),
    )


def schedule_counts(schedule: Iterable[TrialCondition]) -> dict[str, int]:
    """Return deterministic condition counts."""

    counts: dict[str, int] = {}
    for condition in schedule:
        counts[condition.name] = counts.get(condition.name, 0) + 1
    return dict(sorted(counts.items()))


def candidate_signal_matrix(
    conditions: Sequence[TrialCondition],
) -> tuple[tuple[str, ...], NDArray[np.float64]]:
    """Return standardized candidate columns for rank/collinearity diagnostics."""

    statistics = _reference_statistics(conditions)
    columns = []
    for hypothesis in HYPOTHESIS_NAMES:
        mean, scale = statistics[hypothesis]
        columns.append(
            np.asarray(
                [
                    (condition_signals(condition)[hypothesis] - mean) / scale
                    for condition in conditions
                ],
                dtype=float,
            )
        )
    return HYPOTHESIS_NAMES, np.column_stack(columns)


def design_diagnostics(
    conditions: Sequence[TrialCondition],
) -> Mapping[str, float | int]:
    """Return rank, condition number, and maximum candidate correlation."""

    _, matrix = candidate_signal_matrix(conditions)
    correlation = np.corrcoef(matrix, rowvar=False)
    finite = np.isfinite(correlation)
    off_diagonal = np.abs(
        correlation[
            ~np.eye(correlation.shape[0], dtype=bool) & finite
        ]
    )
    return {
        "rank": int(np.linalg.matrix_rank(matrix)),
        "condition_number": float(np.linalg.cond(matrix)),
        "maximum_absolute_correlation": (
            float(np.max(off_diagonal)) if off_diagonal.size else 1.0
        ),
    }
